name: Build Android APK

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install dependencies
      run: npm install

    - name: Build Web App
      env:
        VITE_FIREBASE_API_KEY: "AIzaSyBEMQvEEC6C35pg8uN5q24v3hTs5RkWAFk"
        VITE_FIREBASE_AUTH_DOMAIN: "foobar-10-6c7e7.firebaseapp.com"
        VITE_FIREBASE_PROJECT_ID: "foobar-10-6c7e7"
        VITE_FIREBASE_STORAGE_BUCKET: "foobar-10-6c7e7.firebasestorage.app"
        VITE_FIREBASE_MESSAGING_SENDER_ID: "101858911871"
        VITE_FIREBASE_APP_ID: "1:101858911871:web:546e08e7018a439a06c14a"
      run: npm run build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Build Android APK
      working-directory: ./android
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Foobar10-App-Debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
